Part 1a
dnbaumann/PFMCPP_Project3 pull request #1
Opened 2022-02-06 22:38 UTC by dnbaumann

Please review my commit for the finished part 1a.  Thank you.

2022-02-07 21:04 UTC, matkatmusic requested changes
2 changes needed
The first was not completed when you worked on Part 1c:
```
2) write the name of the primitive type you'll be using after each 
    property in UDTs 1-4:
    pick properties that can be represented with 
    'int float double bool char std::string'.
    example: 
        Display:
            Number of Pixels (int)
            Amount of Power consumed (milliwatt-hours) (float)
            Brightness (double)
            area in cm2 (int)
            brand (std::string)
```

The second change needed:
```
You've just defined 10 UDTs!
4 of them are unrelated (UDTs 1-4).
5 of them form the sub-objects that make up the 10th UDT. 

Move them below this block comment and put them in numerical order 
(1 - 10).
```
It says "Move", not copy.  
You need to **delete** the ones written before line 460
- [ ] revise

2022-02-07 21:38 UTC, matkatmusic approved these changes

2022-02-08 02:48 UTC, matkatmusic approved these changes

2022-02-08 02:49 UTC, matkatmusic requested changes
I have added the next set of instructions!

Code up your UDTS!!

2022-02-09 01:38 UTC, dnbaumann commented
Hi, Please take a quick look at the corrected first example.  certainly not muscle memory yet so I need to do some more once this one is correct.

2022-03-10 21:31 UTC, closed without merging